const userTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',
  AUTH_RESET_FORM: 'AUTH_RESET_FORM',
};

export default userTypes;
